### ISSUE TITLE
DllNotFoundException: enet

### ISSUE THREAD

**Issue by bureto** [nxrighthere/ENet-CSharp#1]
Hi, thanks for this library it is just what I needed :). 

I am using it in the unity editor right now and it is giving `DllNotFoundException: enet`

**What I have done:**

- I downloaded the zip and copied the source folder into my project
- After I got this error I tried putting the dll's in the _Assets/Plugins_ folder
- that didn't work either so I tried putting it in the root project folder

Now I am stumped so I you guys can help me out.
Thanks!

**Comment by nxrighthere** [comment]
You just downloaded the whole master branch and put it your project? It will not work this way. You should download the package for Unity from the release section or compile the native library by yourself.

I think I should mention that in the readme.

**Comment by bureto** [comment]
Wow thanks for the quick reply! 
I hope you don't mind if I ask here:
What is the purpose of `while (!Console.KeyAvailable) {` ? And what can I use instead (for some reason even with `System `included it says `The type name 'KeyAvailable' does not exist in the type 'Console'`)

I am a big noob and I was going through the code and couldn't find what to do instead. I am guessing it is a loop that just updates the status of the client?
Sorry if this is dumb question.

**Comment by bureto** [comment]
Ahh nevermind I think I got it.

**Comment by nxrighthere** [comment]
No problem, I'll explain.

You shouldn't use the console API in Unity. Instead, you can put the service function into the game loop `Update() { }`, and call it in a non-blocking mode without any timeout `server.Service(0, out Event netEvent);`. Also, instead of `Console.WriteLine` you should use `Debug.Log`.

ENet can be used in a independent thread or long running task, but since you are beginner, just stick with the game loop.
