### ISSUE TITLE
What are channel ids for?

### ISSUE THREAD

**Issue by bureto** [nxrighthere/ENet-CSharp#18]
I am guessing they are just meant for organizing your packets sent and received. Right now I have all my packet sent on channel id `0` and everything works great on localHost. Wondering if it is important to make use if different channel ids (like maybe having all movement packets sent on a separate one). Maybe it is important to reduce congestion or something?

Just been wondering for a while and figured I'd finally ask lol.
Thanks :)

**Comment by nxrighthere** [comment]
> Wondering if it is important to make use if different channel ids (like maybe having all movement packets sent on a separate one).

Absolutely. Using different channels, you will get lower latencies because the delivery of data in one channel will not stall the delivery in others. On top of that they are independently sequenced, so you can separate your networking logic across them for stuff like state updates, gameplay mechanics, chat messages, and so on.
