### ISSUE TITLE
Should I multithread?

### ISSUE THREAD

**Issue by bureto** [nxrighthere/ENet-CSharp#31]
First off sorry for the loose question, it kinda has to do with the library though so I thought I would ask.

I have been testing my game and it is working great with a couple of people connected, but I am not too sure what the best practices are for handling more players. I seems that many people talk about multi-threading their server's, but after reading [this](https://www.quora.com/Why-must-the-server-be-multi-threaded) 
> By having a single process receive requests, bind the requests to the requesting machine and queueing the result,

I am not sure if I should. 
I am running it on Amazon Web Services free tier, and it is apparently capable of multithreading, but what would you recommend? The library is working great on single thread, but just curious if you guys have tried (recommend) multithreading? 

**edited part:**
By multithreading I am talking about multithreading the packets sent/recieved on the server. 

And the reason why I ask is I am unsure if this library is meant for that sorta thing, or if it is good to go.
For example:
I didnt fully understand what the quora guy was talking about, but wondering if the library handles the "connection tracking"? 

> One process can track 65,000+ inbound connections

Thanks :)

**P.S.**
Thanks so much for making this library nxrighthere! It is great and is helping me a lot :)

**Comment by nxrighthere** [comment]
> I am running it on Amazon Web Services free tier, and it is apparently capable of multithreading, but what would you recommend? The library is working great on single thread, but just curious if you guys have tried (recommend) multithreading?

It depends on workload, you will not benefit from multi-threading in some cases if your game has moderate network activity, and the code with a custom logic is processed fast. ENet itself is very fast, the only things that might slow down everything is a custom logic on top.

Multi-threading is not an easy task, and it might drive you crazy if you are not experienced enough. You need a strict acknowledgment where are things passed by value and reference, where memory might change in one thread while you try to access it in another, how to make a proper inter-threading communication and many other stuff.

ENet is not thread-safe, and you will not see in this repository locks/mutexes. There's only two things that might be used safely across threads: `Peer.ID` since the ID is cached and struct is passed by value, and `Library.Time` which is utilizes atomic operations internally.

Here ([1](https://github.com/nxrighthere/ENet-CSharp/issues/25#issuecomment-434784816), [2](https://github.com/nxrighthere/ENet-CSharp/issues/27#issuecomment-436139918)) you can find some notes about multi-threading with ENet.

> Thanks so much for making this library nxrighthere! It is great and is helping me a lot :)

You welcome!

**Comment by nxrighthere** [comment]
I wrote some stuff about multi-threading with ENet [here](https://github.com/nxrighthere/ENet-CSharp#multi-threading). Hope it helps, if you are going to do this.
