### ISSUE TITLE
Common mistakes during integration

### ISSUE THREAD

**Issue by nxrighthere** [nxrighthere/ENet-CSharp#45]
Since newcomers make the same mistakes over and over again, and people are reading the API reference not careful enough, I will collect all the common mistakes here.

1. `Packet.Dispose()` called right after sending a packet.

Never dispose a packet after enqueuing it for sending, ENet does that for you automatically, otherwise, memory access failure will occur.

2. Channels limit didn't match at the endpoints.

Always make sure that the channel limit set to the same value at the endpoints using `Host.Create()` and `Host.Connect()` functions, otherwise, packets will not be delivered on disabled channels.

3. Round-trip time is unstable even on localhost.

This is the first indication that the `Host.Service()` is not called [often enough](https://github.com/nxrighthere/ENet-CSharp/issues/40#issuecomment-454958843). Make sure that the service and events are processed [continuously](https://github.com/inexorgame/sauerbraten/blob/891b8dd4bd1bb2fa05a4a6ac56ef46f097a3b024/src/engine/server.cpp#L662) and nothing prevents the ENet to shuttle packets across peers.

4. Latency gets higher relatively to a count of concurrent connections.

Make sure that only the actual payload is sent and not a whole buffer, a packet should be created with the correct length using the `Packet.Create()` function. Check that the ENet is not overwhelmed with large [reliably fragmented](https://github.com/nxrighthere/ENet-CSharp#packetflags) packets.

5. The host is not flushed after the service is no longer in a loop.

Always flush the host before the end of a session to ensure that all queued packets and protocol commands were sent to its designated peers.

**Comment by kersk** [comment]
Running into Host creation errors? Don't forget to call ENet.Library.Initialize();

**Comment by nxrighthere** [comment]
Unity users can use [this](https://github.com/nxrighthere/ENet-CSharp/issues/46) basic example for simple tests.

**Comment by tzurE** [comment]
Hi, a question that I was not sure where to ask.
I've set up everything, and my client can connect to my server and all. But I'm not sure how to continue from here.

I declared my client in ait in a new function. Now, I'm trying to understand the best practice to work with ENET.
in order to actually send data to my server, I'll need to prepare a packet before, connect, send, and wait for a reply. But I need a way to keep adding more packets and send them.
Should I run the entire event while inside a separate thread, and on another one use client.Send() to enqueue a packet?

**Comment by Vincenz099** [comment]
Hey tzurE, you should for sure not have multiple threads interact with enet, because it's not supposed to be used that way.

To have one dedicated thread for enet is recommended though.

To keep adding new packets and still listening you can use single producer single consumer circular threadsafe buffers, where you enqueue commands/packets from your main thread, dequeue in your enet thread, send them off, and keep listening for new data with enet.service, and repeat. whilst in the enet thread any data or event that comes in is pushed in another thread safe ringbuffer and read from your main thread.

**Comment by tzurE** [comment]
Thanks @Vincenz099 !
I would appreciate any working examples of this with Enet, as I'm fairly new to developing a circular threadsafe buffer.

**Comment by Vincenz099** [comment]
This is a good ringbuffer to use. 
https://github.com/dave-hillier/disruptor-unity3d

A sniplet example how to get that stuff to work bit based on what I do, Not the most optimised, not using spans etc but maybe it will help you on the way.:
https://gist.github.com/Vincenz099/dc2ebd56a211a1c7ff4c9d382dbea0c1

**Comment by nxrighthere** [comment]
This [multi-heading strategy](https://github.com/nxrighthere/ENet-CSharp#multi-threading) is explained in the readme.

**Comment by tzurE** [comment]
@nxrighthere , I agree, but it should be noted that this is the bast practice\best way to use Enet. Because as far as I understand(I could be wrong), my client does not even start without running the event loop after connect, so interacting with the client while he receives and sends messages is a basic usage scenario of any Enet Client.
I suggest adding a "Best practice" and an example of queueing packets. I'll try to write something like that myself later and see for myself.

**Comment by nxrighthere** [comment]
> my client does not even start without running the event loop after connect, so interacting with the client while he receives and sends messages is a basic usage scenario of any Enet Client.

Until you manually flush the host - yes. The service function does that for you automatically this is one of its tasks.

> I suggest adding a "Best practice" and an example of queueing packets. I'll try to write something like that myself later and see if I understand it correctly.

Enqueuing packets for sending is an extremely fast operation, nothing to optimize/parallelize there.

**Comment by tzurE** [comment]
> Until you manually flush the host - yes. The service function does that for you automatically this is one of its tasks

So either way, my client has to call host.flush() every time I have some queued packets. Which is not that obvious from the example that shows only how to connect and listen for events. I ask - where is the recommended place to call "Flush" **inside** that event loop? as far as I understand we'll only get to the client.Flush() in the last line if we got some packet from the server before that.

> Enqueuing packets for sending is an extremely fast operation, nothing to optimize/parallelize there.

It's not about making it faster, but as I asked in the previous line - where is the best place to start that dequeue and send/flush process. Maybe it's entirely outside this loop?

**Comment by nxrighthere** [comment]
> So either way, my client has to call host.flush() every time I have some queued packets. Which is not that obvious from the example that shows only how to connect and listen for events. I ask - where is the recommended place to call "Flush" inside that event loop? as far as I understand we'll only get to the client.Flush() in the last line if we got some packet from the server before that.

Example speaks for itself, is just an example, for integration you use API reference where said: _Host.Flush() sends any queued packets on the specified host to its designated peers._ So you can call it when you want to send enqueued packets immediately without waiting for a next service iteration with all the consequences.

> It's not about making it faster, but as I asked in the previous line - where is the best place to start that dequeue and send/flush process. Maybe it's entirely outside this loop?

Where it's required according to a logic of your application.

**Comment by tzurE** [comment]
Thanks for all of your help :)
