### ISSUE TITLE
Package Level Compression

### ISSUE THREAD

**Issue by jdzied** [nxrighthere/ENet-CSharp#54]
First of all, thanks for the great work on the library and all the explanations - they helped a lot.

I was wandering if it makes sense to use package level compression instead of connection level compression.

IE: I would like to transfer a png Image and some other data - there is no need to compress the png image again (which will cause lag and eventually lead to a disconnect) but the other data will be nice to be compressed.

Since the "compressed" information is in the package header anyway - why not use compression with the funktion create_e_net_package? This could also save some additional time if the package creation is threaded.

Do you think this might be a good approach?

**Comment by nxrighthere** [comment]
> I was wandering if it makes sense to use package level compression instead of connection level compression.

The primary goal of packet-level compression is to crunch all data in the internal buffer before sending it to a peer and everything can be compressed at once within a single call. LZ4 will be applied only for data that larger than 64 bytes, ENet will automatically determine if a packet was really compressed or not before adding an appropriate flag to it. It's done transparently and efficiently using a self-growing compression buffer.

> IE: I would like to transfer a png Image and some other data - there is no need to compress the png image again (which will cause lag and eventually lead to a disconnect) but the other data will be nice to be compressed.

Yes, my initial plan was to add per packet compression, but this will work well only at application-level because adding this functionality internally to ENet is problematic, it will break some stuff, and it will work not that efficient as its implemented now. If you want to use compression on demand and parallelize it, it's better to compile ENet without `ENET_LZ4` definition and compress payloads as you like at application-level if that is convenient for you.

> First of all, thanks for the great work on the library and all the explanations - they helped a lot.

Glad to hear, cheers.
