### ISSUE TITLE
Question about which way to use.

### ISSUE THREAD

**Issue by jclitwin** [nxrighthere/ENet-CSharp#55]
First, @nxrighthere thanks alot for this amazing project and for always is helping everyone.

Basically, I have a simple multiplayer game with an already developed structure:
-> Login Server
-> Lobby Server
-> Room Server

But all the servers use TCP, but basically I want to rewrite the Room Server and convert it to UDP. I do not want to have to rewrite everything just the Room Server, which is where the matches happens. My question is:

What would be the best way to use enet?

- Create a host that supports multiplayer and create something to separate them from each game;
- Create a host for each room itself (around 32 slots);

Or would you have a better suggestion?

Thanks,
Cheers!

**Comment by nxrighthere** [comment]
> Create a host for each room itself (around 32 slots);

Creating a separate host on a different port for each room should work fine, your lobby server tracks which server is free to start a new session. You need to monitor at what point resources of your server instance will not be enough to handle N rooms due to the fact that the player's latency noticeable grows.

> First, @nxrighthere thanks alot for this amazing project and for always is helping everyone.

Thanks, you're welcome.
