### ISSUE TITLE
Question about server.Service timeout.

### ISSUE THREAD

**Issue by bureto** [nxrighthere/ENet-CSharp#7]
I have a question about :

> The timeout parameter set to 0 means non-blocking which required for cases where the function is called in a game loop.

What would be a reason to _have_ a timeout set?  Right now I have it set to 0 and its running in Update which I guess means it processes the packets received each frame. Is that the 'best' way to do it or, based off the quote above, the only way to do it in Unity? I was thinking another way (maybe) would be to have it in the `FixedUpdate()` function running on an interval of, say 20ms; and then having the `timeout `parameter set to that same interval length (20ms). Not even sure if that is how it works but just a guess. Just curious if it matters that much. My guess is that the running it without a timeout improves network performance, at a cost of cpu. And then vice versa, running it delayed with a timeout might congest network and maybe improve cpu usage? 

Sorry if this is not how it works at all haha.

**Comment by nxrighthere** [comment]
> Right now I have it set to 0 and its running in Update which I guess means it processes the packets received each frame. Is that the 'best' way to do it

It's only reasonable when the service function called in a game loop, and resource-intensive work is not performed in it. This way you don't need to bother with concurrency since everything is done synchronously with a single-threaded code.

> based off the quote above, the only way to do it in Unity?

No, it's not, but acceptable for games with moderate network activity.

An alternative way is to make a separate thread/long-running task which will process network events and data independently of a game loop, and stuff will be dispatched to the main thread. But this is a harder way since it requires an knowledge in parallelism.

> I was thinking another way (maybe) would be to have it in the FixedUpdate() function running on an interval of, say 20ms; and then having the timeoutparameter set to that same interval length (20ms). 

It doesn't change the fact that the code will be performed synchronously. I don't recommend to do this because the service function must be called frequently. It's very important for multiplayer games to receive data as soon as possible. You have to fight with latency and delay, not bring it even more.

> My guess is that the running it without a timeout improves network performance, at a cost of cpu.

Exactly, but this cost is nothing compared to the game logic itself in most cases.

> And then vice versa, running it delayed with a timeout might congest network and maybe improve cpu usage?

If you care about the performance, concurrency is the way to go.
